name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    ci:
        name: Building, linting, testing on node ${{ matrix.node.version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node:
                    - version: '16.x'
                      install-npm: false
                    - version: '18.x'
                      install-npm: false
                    - version: '20.x'
                      install-npm: false
                    - version: '22.x'
                      install-npm: false
                    - version: '24.x'
                      install-npm: false
                os: [ubuntu-latest]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6

            - name: Use Node ${{ matrix.node.version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node.version }}

            - name: Setup npm@6.12.0
              if: ${{ matrix.node.install-npm }}
              run: npm i -g npm@6.12.0

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm test -- --ci --coverage --maxWorkers=2

            - name: Build
              run: npm run build
